// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwttyYYayrbZnKiN3Me8LFmTjoR7zMO4I',
    appId: '1:946902067778:web:fe72e01a9fae95033b1bdb',
    messagingSenderId: '946902067778',
    projectId: 'chatflow-633af',
    authDomain: 'chatflow-633af.firebaseapp.com',
    storageBucket: 'chatflow-633af.firebasestorage.app',
    measurementId: 'G-SD4CBQTYPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8aJ5b-jAMr28FoJrvjiLBHttX6znhI0s',
    appId: '1:946902067778:android:ee50754dafbee4703b1bdb',
    messagingSenderId: '946902067778',
    projectId: 'chatflow-633af',
    storageBucket: 'chatflow-633af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD31K2mWRlkSaE7Xl7nIZBYuSyNqT7bu0c',
    appId: '1:946902067778:ios:1a8bc53c81bc6a013b1bdb',
    messagingSenderId: '946902067778',
    projectId: 'chatflow-633af',
    storageBucket: 'chatflow-633af.firebasestorage.app',
    iosBundleId: 'com.example.chatFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD31K2mWRlkSaE7Xl7nIZBYuSyNqT7bu0c',
    appId: '1:946902067778:ios:1a8bc53c81bc6a013b1bdb',
    messagingSenderId: '946902067778',
    projectId: 'chatflow-633af',
    storageBucket: 'chatflow-633af.firebasestorage.app',
    iosBundleId: 'com.example.chatFlow',
  );
}
